#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# hostdestroy
#
# This file is run on the host, and can be used to do things like
# destroy docker volumes (e.g. docker volume rm dr-helloworld-datavol )
#
#


function p {
   echo "$1" >&2
}

p " "
p "dr/destroy SERVICENAME IMAGE        -- automatically run on host when destroyed"
p "dr/destroy  ${SERVICENAME} ${IMAGENAME}"
p " "
