#!/bin/bash

SERVICENAME="$1"
IMAGENAME="$2"


function p {
   echo "$1" >&2
}

p " "
p "dr/enter SERVICENAME IMAGE"
p "dr/enter  ${SERVICENAME} ${IMAGENAME}"
p " "


# This script is run on the host.
# It launches the docker container and runs our hello world command.

docker run -i -t --name="${SERVICENAME}-enter" -h "${HOSTNAME}"     \
               -v "dr-${SERVICENAME}-config:/config"                   \
               ${IMAGENAME} /bin/bash
docker rm "${SERVICENAME}-enter"