#!/bin/bash

# install
#
# This file is run on the host, and can be used to do things like
# set up docker volumes (e.g. docker volume create dr-helloworld-datavol )
#
#

SERVICENAME="$1"
IMAGENAME="$2"


function p {
   echo "$1" >&2
}

p " "
p "dr/install SERVICENAME IMAGE"
p "dr/install  ${SERVICENAME} ${IMAGENAME}"
p " "

