#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# restore
#
# This file is run on the host, and restores any configuration or data
# that is outside /dr/config from the backup in RESTOREPATH.
#

RESTOREPATH="$1"

function p {
   echo "$1" >&2
}

p " "
p "dr/restore SERVICENAME IMAGE PATH   -- restore from files in PATH"
p "dr/restore  ${SERVICENAME} ${IMAGENAME} ${RESTOREPATH}"
p " "

cat /config/note.txt
cat /data/note.txt
