#!/bin/bash

# restore
#
# This file is run on the host, and restores any configuration or data
# that is outside /dr/config from the backup in RESTOREPATH.
#

SERVICENAME="$1"
IMAGENAME="$2"
RESTOREPATH="$3"

function p {
   echo "$1" >&2
}

p " "
p "dr/restore SERVICENAME IMAGE PATH   -- restore from files in PATH"
p "dr/restore  ${SERVICENAME} ${IMAGENAME} ${RESTOREPATH}"
p " "
