#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# backup
#

BACKUPPATH="$1"

function p {
   echo "$1" >&2
}

p " "
p "dr/backup  SERVICENAME IMAGE PATH   -- backup to files in PATH"
p "dr/backup  ${SERVICENAME} ${IMAGENAME} ${BACKUPPATH}"
p " "


echo "Restore succeeded! Our note.txt file was automatically backed up for us." > "$BACKUPPATH/note.txt"



docker run -i -t --name="${SERVICENAME}-run" "${DOCKEROPTS[@]}" "${IMAGENAME}" \
               bash -c 'echo "Restore of config succeeded!" > /config/note.txt && echo "Restore of data succeeded!" > /data/note.txt'
docker rm "${SERVICENAME}-run" >/dev/null 2>&1



