#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"


function p {
   echo "$@" >&2
}

p " "
p "drunner/enter" $@
p " "


# This script is run on the host.
# It launches the docker container and runs our hello world command.

docker run -i -t --name="${SERVICENAME}-enter" -h "${HOSTNAME}"     \
               ${DOCKEROPTS[@]}                                     \
               ${IMAGENAME} /bin/bash "$@"
docker rm "${SERVICENAME}-enter" >/dev/null

