#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

cat <<EOF >&2
   
NAME
   ${SERVICENAME} - testing stuff
 
DESCRIPTION
   A testing thing. Built from ${IMAGENAME}.
EOF


function p {
   echo "$1" >&2
}

p " "
p "dr/help SERVICENAME IMAGE"
p "dr/help  ${SERVICENAME} ${IMAGENAME}"
p " "

