#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# This script is run on the host.
# It launches the docker container and runs our hello world command.

docker run -i -t --name="${SERVICENAME}-run" -h "${HOSTNAME}"        \
               "${DOCKEROPTS[@]}"                                      \
               "${IMAGENAME}" helloworld "${SERVICENAME}" "${IMAGENAME}"
RVAL=$?
docker rm "${SERVICENAME}-run" >/dev/null 2>&1

function p {
   echo "$1" >&2
}

p " "
p "dr/run SERVICENAME IMAGE"
p "dr/run  ${SERVICENAME} ${IMAGENAME}"
p " "

exit $RVAL
