#!/bin/bash
set -o nounset
source "$( dirname "$(readlink -f "$0")" )/_variables"

# This script is run on the host.
# It launches the docker container and runs our hello world command.


function title {
   echo " ">&2
   echo " ">&2
   if [ "$#" -eq 1 ]; then
      echo -e "\e[1;4;32m${1}\e[0m">&2
   else
      echo -e "\e[1;4;31m${1}\e[0m">&2
   fi      
   echo " ">&2
}

RVAL=0
#TESTIMAGES=("drunner/test" "drunner/helloworld" "drunner/simplesecrets" "drunner/samba" "drunner/ansible" "drunner/minecraft")
TESTIMAGES=("drunner/test:dev" "drunner/helloworld:dev" "drunner/simplesecrets:dev")

for TESTIMAGE in "${TESTIMAGES[@]}"; do
   ${SERVICENAME} test ${TESTIMAGE}
   if [ $? -ne 0 ]; then RVAL=1 ; fi
done

if [ $RVAL -eq 0 ]; then
   title "ALL TESTS PASSED."
else
   title "TESTS FAILED." "FAIL"
fi

exit $RVAL

# http://patorjk.com/software/taag/#p=display&f=Univers&t=dRunner
# http://shapecatcher.com/
# http://misc.flogisoft.com/bash/tip_colors_and_formatting

